# Generated by Django 4.1.4 on 2023-08-03 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='posts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('post_designation', models.CharField(max_length=300)),
                ('Experience', models.CharField(max_length=100)),
                ('Salary', models.CharField(max_length=100)),
            ],
        ),
    ]
