# Generated by Django 4.1.4 on 2023-08-03 07:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_posts'),
    ]

    operations = [
        migrations.RenameField(
            model_name='posts',
            old_name='Experience',
            new_name='experience',
        ),
        migrations.RenameField(
            model_name='posts',
            old_name='Salary',
            new_name='salary',
        ),
    ]
